### ISSUE TITLE
popup_select_first does not work

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#399]
the problem with the option popup_select_first. g:jedi#popup_select_first = 0 did not affect

my vim settings:

set completeopt=menuone,longest

let g:jedi#show_call_signatures = 0
let g:jedi#use_tabs_not_buffers = 0
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 1

previous issue: https://github.com/davidhalter/jedi-vim/issues/179
video demonstration: https://dl.dropboxusercontent.com/u/5837324/jedi-vim-bug.mov

**Comment by davidhalter** [comment]
cc @blueyed because you have just worked on it.

**Comment by davidhalter** [comment]
I'm actually having problems with the new implementation as well.

```
let g:jedi#popup_select_first = 1
completeopt=menuone,longest,preview
```

**Comment by blueyed** [comment]
Thanks for the report and sorry for breaking it.. :)

Should be fixed in master, please let me know if it isn't.

**Comment by moorepants** [comment]
Fixed for me. Thanks.

**Comment by blueyed** [comment]
@moorepants 
Thanks for reporting back, and sorry again for breaking it.. :)

@davidhalter
I'd appreciate some test for this.
Do you feel like adding one?

Regarding the test suite, I think that using https://github.com/junegunn/vader.vim might be good, too - or even better in general.

**Comment by aliev** [comment]
@blueyed works!

**Comment by davidhalter** [comment]
> Do you feel like adding one?

No :) I still don't understand what the problems where, but I agree that we should test it. There's just so many scenarios now.

> Regarding the test suite, I think that using https://github.com/junegunn/vader.vim might be good, too - or even better in general.

I feel like I chose vim-vspec, because it looks more organized (and it's easy to clean/initialize for a group of tests. Vader would be better, because it's smaller. If you want to replace it, I would be interested in the advantages of vader.

**Comment by tony** [comment]
Jedi-vim at  625c568 will always select and print the first entry if you have ``longest`` in ``completeopt``.

Assuming:

```viml
let g:jedi#show_call_signatures = 0
let g:jedi#use_tabs_not_buffers = 0
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 1
```

To fix, ``:set completeopt=-longest``.

**Comment by blueyed** [comment]
@tony 
Seems to be related to this code:
https://github.com/davidhalter/jedi-vim/blob/625c568b1249db8c5f1b06a1f9371c06ba2d08b5/autoload/jedi.vim#L486-L501

I think you want to have `noinsert` or `noselect` in `'completeopt'`, no?

Are you using deoplete by chance?
