### ISSUE TITLE
vim freezes on triple-quote

### ISSUE THREAD

**Issue by reinhrst** [davidhalter/jedi-vim#448]
Considering the following file:

    t("" "
    with:
    t

When I put my cursor between the two ""'s and press `"`, to make it a triple quote, vim freezes. This is the minimal example I could come up with, perhaps a bit contrived, but it happens to me multiple times a day in real-world files. Vim will go to 100% CPU and listens to nothing but a SIGKILL.

I'm running MacVim 7.4-77, with python 3.4.3 (LLVM 6.1.0, clang-602.0.53) on OSX Yosemite. It happens both in the console and in the windowed macvim. I'm not sure on my jedi-vim version, jedi version is 0.9.0. Except for vundle and jedi-vim, my .vimrc is empty.

I notice that if I switch off call signatures, the problem goes away (at least in my testcase)

    let g:jedi#show_call_signatures = 0

`let g:jedi#show_call_signatures = 2` does not solve the problem

**Comment by reinhrst** [comment]
I tried to reproduce the error in jedi itself, but without luck; this just works:

    >>> jedi.api.Script('''t(""" "\nwith:\nt\n''', 1, 5).call_signatures()
    []

**Comment by davidhalter** [comment]
I cannot reproduce it. Did you try to update jedi-vim to the latest dev branch?

**Comment by reinhrst** [comment]
Indeed I had not. The problem turned out to be in jedi, although I can't say I understand what happened:
I had installed an older version of jedi that claimed to be 0.9.0 (though import jedi; jedi.__version__), but was actually jedi#4bb41b6096. Newer versions (including the tagged 0.9.0 seemed fine). The problem was solved in jedi#9024825. Apologies for the confusion and thanks for getting back to me.

**Comment by davidhalter** [comment]
Thanks for the research!!

I don't think you were wrong. The newer versions that are tagged `0.9.0` probably should be `0.9.1-alpha` or something like that, because they are just dev versions. So this bug still exists in the official pypi repositories.
